//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRestApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public int No { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<bool> complete { get; set; }
    }
}
